name: foodly_clean_arc
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  equatable: ^2.0.5
  cupertino_icons: ^1.0.2
  modal_progress_hud_nsn: ^0.5.1
  page_transition: "^2.0.9"
  font_awesome_flutter: ^10.2.1
  introduction_screen: ^3.0.2
  smooth_page_indicator: ^1.0.0+2
  expandable: ^5.0.1
  provider: ^6.0.4
  geolocator: ^13.0.1
  loading_indicator: ^3.1.0
  http: ^0.13.5
  firebase: ^9.0.3
  firebase_core: ^3.6.0
  form_field_validator: ^1.1.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  flutter_facebook_auth: ^6.0.4
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  flutter_riverpod: ^2.2.0
  circular_countdown_timer: ^0.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/onboarding_images/
    - assets/search_images/
    - assets/search_results/